version: "3.7"

services:
    redis:
        image: redis:alpine
        command: redis-server --requirepass secret
        ports:
            - "6379:6379"
    app:
        depends_on:
            - redis
        build: .
        container_name: teste
        ports:
            - 8080:8080
        volumes:
            - .:/usr/app
